demo:
  service:
    version: 1.0.0


server:
  port: 8081

spring:
    application:
      name: dubbo-provider

dubbo:
  scan:
    base-packages: com.sea.dubbo.provider.service
  protocol:
        name: dubbo
        port: 12345
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

